# 🧮 Actividad: Análisis exploratorio con NumPy

*(EDA sin Pandas — antesala a Pandas y JAX NumPy)*

---

## 🧾 Contexto del dataset

Se trabajará con un dataset sintético que simula **información de empleados**:

* ID
* Edad
* Salario mensual
* Años de experiencia
* Horas de trabajo por semana
* Nivel educativo (0 a 4)
* Satisfacción (0–10, con valores faltantes o atípicos)

Generaremos los datos con `np.random`, así todos tendrán el mismo formato.

In [9]:
import numpy as np

np.random.seed(42)
n = 1000

ids = np.arange(1, n+1)
edad = np.random.randint(18, 65, size=n)
salario = np.random.normal(2500, 800, size=n)
experiencia = np.clip(edad - np.random.randint(18, 30, size=n), 0, None)
horas = np.random.normal(40, 5, size=n)
nivel = np.random.randint(0, 5, size=n)
satisfaccion = np.random.normal(7, 2, size=n)

# Añadimos valores atípicos y NaN
salario[np.random.randint(0, n, 10)] *= 4
satisfaccion[np.random.randint(0, n, 15)] = np.nan

data = np.column_stack([ids, edad, salario, experiencia, horas, nivel, satisfaccion])

In [8]:
import numpy as np

# Crear un array estructurado con nombres de columnas
data2 = np.array([
    (1, 2.5, 'A'),
    (2, 3.6, 'B')
], dtype=[('id', 'i4'), ('valor', 'f4'), ('categoria', 'U1')])

# Obtener nombres de columnas
column_names = list(data2.dtype.names)

print("Nombres de columnas:", column_names)

Nombres de columnas: ['id', 'valor', 'categoria']


### 🧠 **Tarea 1: Descripción básica del dataset**

1. Muestra el número de filas y columnas del array `data`.
2. Muestra los nombres de las columnas.
3. Obtén los primeros 5 registros.

➡️ Objetivo: entender cómo están dispuestos los datos y su estructura.

---



In [29]:
print("número de filas y columnas:", data.shape)
print("Tipo de las columnas:")
print("Nombre de las columnas:", [x.dtype.names for x in data[0]])  
np.set_printoptions(precision=2, suppress=True)
print(f"Primeras 5 filas:{data[:5]}")

número de filas y columnas: (1000, 7)
Tipo de las columnas:
Nombre de las columnas: [None, None, None, None, None, None, None]
Primeras 5 filas:[[   1.     56.   3305.03   29.     40.96    1.      7.86]
 [   2.     46.   2038.49   24.     40.34    4.      8.76]
 [   3.     32.   3168.55   11.     34.72    3.      6.16]
 [   4.     60.   1596.23   37.     45.29    3.      5.63]
 [   5.     25.   2923.84    0.     41.02    4.      9.44]]


### 📏 **Tarea 2: Tipos y rangos**

1. Identifica los tipos de datos de cada columna (`int`, `float`, etc.).
2. Muestra el valor mínimo y máximo de cada variable numérica.
3. Calcula la media, mediana y desviación típica de **edad** y **salario**.

➡️ Objetivo: practicar operaciones estadísticas básicas.

---



In [27]:
# Ver columnas con NaN
nan_columns = np.any(np.isnan(data), axis=0)
print("Columnas con NaN:", np.where(nan_columns)[0])

print("Número de Nan en cada columna:", np.sum(np.isnan(data), axis=0))

Columnas con NaN: [6]
Número de Nan en cada columna: [ 0  0  0  0  0  0 15]


In [31]:
np.set_printoptions(precision=2, suppress=True)
#1 
tipos = [x.dtype for x in data.T]
print(tipos)
print("Tipo de las columnas:",[type(x[0]) for x in data])
#2. 
print(f"Máximos:{np.nanmax(data, axis=0)}") # Usar np.nanmax para ignorar NaN
print(f"Máximos:{data.max(axis=0)}") # No ignorar NaN
print(f"Mínimos:{np.nanmin(data, axis=0)}")

print(f"Medias:{np.nanmean(data, axis=0)}")
print(f"Desviaciones estándar:{np.nanstd(data, axis=0)}")
print(f"Medianes:{np.nanmedian(data, axis=0)}")


[dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64')]
Tipo de las columnas: [<class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, 

### 💭 **Tarea 3: Filtrado de datos**

1. Obtén todos los empleados con salario mayor a 4000 €.
2. Obtén los IDs de quienes trabajan más de 45 h/semana y tienen más de 10 años de experiencia.
3. Calcula el porcentaje de empleados con **nivel educativo ≥ 3**.

➡️ Objetivo: uso de indexado booleano y condiciones combinadas.

---



In [ ]:
#1.
print(f"Empleados con salario > 5000: {np.sum(data[:,2]>4000)}")

### 🧹 **Tarea 4: Limpieza — valores faltantes**

1. Cuenta cuántos valores faltantes (`np.nan`) hay en la columna **satisfacción**.
2. Sustituye los valores `NaN` por la **media** de satisfacción.
3. Comprueba que ya no hay valores faltantes.

➡️ Objetivo: manejo básico de `np.isnan()` y reemplazos condicionales.

---



### ⚠️ **Tarea 5: Detección de outliers**

1. Calcula los **cuartiles (Q1 y Q3)** del salario.
2. Calcula el **rango intercuartílico (IQR)**.
3. Encuentra los valores que están fuera de `Q1 - 1.5*IQR` o `Q3 + 1.5*IQR`.
4. Muestra cuántos outliers hay.

➡️ Objetivo: detección numérica de valores atípicos con operaciones vectorizadas.

---



### 🧰 **Tarea 6: Sustitución o corrección de outliers**

1. Sustituye los salarios outliers por el valor del **percentil 95**.
2. Verifica que ya no hay salarios fuera del rango esperado.

➡️ Objetivo: aplicar `np.where` y percentiles para limpiar valores extremos.

---



### 📊 **Tarea 7: Agrupaciones y resúmenes simples**

1. Calcula el salario medio por **nivel educativo (0–4)**.
2. Calcula la satisfacción media por **grupo de edad**:

   * Menores de 30
   * 30–50
   * Mayores de 50

➡️ Objetivo: practicar máscaras múltiples y operaciones por grupo con NumPy.

---



### 🧩 **Tarea 8: Normalización y escalado**

1. Normaliza la variable **salario** entre 0 y 1.
2. Estandariza (z-score) la variable **horas**.
3. Comprueba media ~0 y std ~1.

➡️ Objetivo: practicar transformaciones de escala (útil para ML más adelante).

---



### 🧮 **Tarea 9: Correlaciones simples**

1. Calcula la **correlación** entre salario y experiencia.
2. Calcula la correlación entre edad y satisfacción.

➡️ Objetivo: usar `np.corrcoef` e interpretar relaciones lineales.

---



### 🧾 **Tarea 10: Estadísticas generales**

1. Muestra para cada columna:

   * Media
   * Desviación estándar
   * Valor mínimo
   * Valor máximo
   * Porcentaje de valores faltantes

➡️ Objetivo: preparar el pensamiento para `df.describe()` y `df.info()` de Pandas.

---



## 💬 Cierre de la práctica

Tras completar todas las tareas:

* Comenta con el grupo **qué operaciones fueron más fáciles con NumPy**.
* Avanza la idea de que **Pandas** automatiza mucho de esto con estructuras **Series** y **DataFrames**, simplificando la limpieza y exploración.

---


#
## 🧰 Sugerencia para ti

Puedes guardar esta práctica como `EDA_numpy.md` y convertirla a notebook con:

In [ ]:
%%bash
jupytext --to notebook EDA_numpy.md

---
