---

# 🧩 ¿Qué es el *broadcasting* en NumPy?

El **broadcasting** es una forma en la que **NumPy permite hacer operaciones entre arrays de distinto tamaño o forma**, **sin necesidad de usar bucles** ni copiar datos.

> 👉 En otras palabras: NumPy “extiende” (broadcast) los arrays más pequeños para que coincidan con la forma del más grande.

---

## 🎯 Idea principal

Supón que quieres sumar una matriz y un número:

In [3]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = 10
C = A + B
C

array([[11, 12, 13],
       [14, 15, 16]])

✅ NumPy entiende que el número `10` se “repite” por toda la matriz:
→ `10` se convierte internamente en `[[10, 10, 10], [10, 10, 10]]`

Resultado:

In [2]:
[[11, 12, 13],
 [14, 15, 16]]

[[11, 12, 13], [14, 15, 16]]

---

## 📏 Regla general del broadcasting

Cuando se operan dos arrays, **NumPy compara sus dimensiones empezando desde la última hacia atrás**:

1. Si las dimensiones son **iguales**, se pueden combinar.
2. Si una de ellas es **1**, se “expande” (broadcast).
3. Si son **diferentes y ninguna es 1**, → ❌ error.

---

## 📚 Ejemplo 1: vector fila + vector columna

In [4]:
a = np.array([[1, 2, 3]])   # forma (1,3)
b = np.array([[10],
              [20],
              [30]])        # forma (3,1)

print(a + b)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


🔹 NumPy expande `a` verticalmente y `b` horizontalmente:

[[1, 2, 3]] → se repite ↓ 3 veces

[[ 1,  2,  3],
 [ 1,  2,  3],
 [ 1,  2,  3]]

 
[[10], 
 [20], 
 [30]] → se repite → 3 veces
[[10, 10, 10],
 [20, 20, 20],
 [30, 30, 30]]


Resultado:

In [ ]:
[[11, 12, 13],
 [21, 22, 23],
 [31, 32, 33]]

Formas compatibles:

(3,1)
(1,3)
↓
(3,3)

---

## 📚 Ejemplo 2: matriz + vector

In [5]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

v = np.array([10,20,30])
print(A + v)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


🔹 NumPy expande el vector `v` por cada fila.
Resultado:

Forma `(3,3)` + `(3,)` → `(3,3)`

[[10,20,30]] → se repite ↓ 3 veces

[[10,20,30],
[10,20,30],
[10,20,30]]
+
[[1,2,3],
 [4,5,6],
 [7,8,9]]
=
[[11,22,33],
 [14,25,36],
 [17,28,39]]


---

## ❌ Ejemplo incompatible

In [6]:
a = np.ones((3,4))
b = np.ones((2,1))
print("Matriz a:")
print(a)
print("Matriz b:")
print(b)
print("Suma de a + b:")
print(a + b)

Matriz a:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Matriz b:
[[1.]
 [1.]]
Suma de a + b:


ValueError: operands could not be broadcast together with shapes (3,4) (2,1) 

Da error porque:

(3,4)
(2,1)

→ ni 3 = 2, ni 4 = 1 → ❌ no hay coincidencia posible.

---

## 🧠 Ejemplo útil: distancia entre puntos

In [ ]:
x = np.array([1, 2, 3])
y = np.array([2, 4, 6])

dist = np.sqrt((x - y)**2)
print(dist)

[1. 2. 3.]


Y también con matrices:

In [ ]:
X = np.array([[1,2,3],
              [4,5,6]])

Y = np.array([[10,20,30]])

print(X * Y)  # Broadcasting

dist = np.sqrt((X - Y)**2)
print(dist)

[[ 10  40  90]
 [ 40 100 180]]
[[ 9. 18. 27.]
 [ 6. 15. 24.]]


En el siguiente ejemplo:
Qué ocurre:

v se expande a (1, 1, 4) → se suma a cada fila de cada bloque.

Resultado: matriz (2, 3, 4) con valores [11, 21, 31, 41] repetidos.

In [5]:
import numpy as np

# Matriz 3D: 2 bloques de 3x4
A = np.ones((2, 3, 4))  # Shape: (2, 3, 4)
print("Matriz A:")
print(A)

# Vector 1D con 4 elementos
v = np.array([10, 20, 30, 40])  # Shape: (4,)
print("Vector v:")
print(v)

# Expansión de dimensiones para broadcasting
# v se expande a (1, 1, 4) para que coincida con A
print("Vector v expandido para broadcasting:")
# Expandimos v a (1, 1, 4) y luego lo repetimos
broadcasted = np.broadcast_to(v.reshape(1, 1, 4), (2, 3, 4))
print(broadcasted) 

# Broadcasting: se suma el vector a cada fila de cada bloque
resultado = A + broadcasted
print("Resultado:")
print(resultado)


Matriz A:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Vector v:
[10 20 30 40]
Vector v expandido para broadcasting:
[[[10 20 30 40]
  [10 20 30 40]
  [10 20 30 40]]

 [[10 20 30 40]
  [10 20 30 40]
  [10 20 30 40]]]
Resultado:
[[[11. 21. 31. 41.]
  [11. 21. 31. 41.]
  [11. 21. 31. 41.]]

 [[11. 21. 31. 41.]
  [11. 21. 31. 41.]
  [11. 21. 31. 41.]]]


Qué ocurre:

E_reshaped se expande a (2, 3, 4) → se suma por bloque.

Cada bloque de D recibe su fila correspondiente de E.

In [6]:
D = np.ones((2, 3, 4))  # Shape: (2, 3, 4)
E = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  # Shape: (2, 4)
print("Matriz D:")
print(D)
print("Matriz E:")
print(E)

# Reshape para que E tenga forma compatible
E_reshaped = E.reshape(2, 1, 4)  # Shape: (2, 1, 4)
print("Matriz E reshaped:")
print(E_reshaped)
# Broadcasting: se suma E a cada fila de D
resultado = D + E_reshaped
print("Resultado:")
print(resultado)

Matriz D:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Matriz E:
[[1 2 3 4]
 [5 6 7 8]]
Matriz E reshaped:
[[[1 2 3 4]]

 [[5 6 7 8]]]
Resultado:
[[[2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]]

 [[6. 7. 8. 9.]
  [6. 7. 8. 9.]
  [6. 7. 8. 9.]]]


In [7]:
import numpy as np

D = np.ones((2, 3, 4))  # Shape: (2, 3, 4)
E = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  # Shape: (2, 4)

# Expandimos E a (2, 1, 4) para que se pueda sumar a D
E_broadcasted = np.broadcast_to(E.reshape(2, 1, 4), (2, 3, 4))

# Sumamos D + E_broadcasted
resultado = D + E_broadcasted

print("E expandido:\n", E_broadcasted)
print("\nResultado:\n", resultado)

E expandido:
 [[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[5 6 7 8]
  [5 6 7 8]
  [5 6 7 8]]]

Resultado:
 [[[2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]]

 [[6. 7. 8. 9.]
  [6. 7. 8. 9.]
  [6. 7. 8. 9.]]]


---

## 🧩 Resumen visual

| Forma A | Forma B | ¿Compatible? | Resultado                    |
| ------- | ------- | ------------ | ---------------------------- |
| (3,3)   | (3,)    | ✅            | Se expande el vector a (3,3) |
| (3,1)   | (1,3)   | ✅            | Resultado (3,3)              |
| (2,3)   | (3,2)   | ❌            | Incompatible                 |
| (5,1,4) | (1,3,1) | ✅            | Resultado (5,3,4)            |

---

## 🎓 En resumen

* NumPy **no copia** realmente los datos, solo “simula” que el array pequeño se repite.
* Ahorra **memoria y tiempo**.
* Es una de las razones por las que NumPy es tan rápido y eficiente.

---