In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

# http://lotto.merseyworld.com/cgi-bin/lottery?days=20&Machine=Z&Ballset=0&order=0&show=1&year=0&display=CSV

In [2]:
df = pd.read_csv("Euromillones.csv")

In [3]:
# Define a correct parse function for your date format
def parse_date(x):
    return pd.to_datetime(x, format="%d,%b,%Y")


# Apply the parse function to combine the columns into a datetime column
df["YYYY_MMM_DD"] = df.apply(
    lambda row: parse_date(f"{row['DD']},{row['MMM']},{row['YYYY']}"), axis=1
)

# Set the new 'Date' column as index if needed
df.set_index("YYYY_MMM_DD", inplace=True)
df.drop(columns=["DD", "MMM", "YYYY"], inplace=True)
# Eliminar espacios en blanco del nombre de las columnas
df = df.rename(columns=lambda x: x.strip())
df = df.iloc[::-1]  # reverse order of rows

In [4]:
df = df.drop(["No.", "Day", "Jackpot", "Wins"], axis=1)


#df.columns = ["N1", "N2", "N3", "N4", "N5", "S1", "S2"]

In [5]:
df.head()

,N1,N2,N3,N4,N5,L1,L2
YYYY_MMM_DD,,,,,,,
2004-02-13,32,16,29,41,36,9,7
2004-02-20,13,50,47,7,39,2,5
2004-02-27,37,19,18,14,31,5,4
2004-03-05,39,37,4,7,33,5,1
2004-03-12,44,47,15,28,24,4,5


In [6]:
df.tail()

,N1,N2,N3,N4,N5,L1,L2
YYYY_MMM_DD,,,,,,,
2024-04-12,45,16,12,2,3,11,2
2024-04-16,39,31,46,29,22,3,7
2024-04-19,10,20,46,40,44,1,3
2024-04-23,9,49,11,6,32,2,10
2024-04-26,47,2,39,20,40,8,4


In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1731 entries, 2004-02-13 to 2024-04-26
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   N1      1731 non-null   int64
 1   N2      1731 non-null   int64
 2   N3      1731 non-null   int64
 3   N4      1731 non-null   int64
 4   N5      1731 non-null   int64
 5   L1      1731 non-null   int64
 6   L2      1731 non-null   int64
dtypes: int64(7)
memory usage: 108.2 KB


In [8]:
df.describe()

,N1,N2,N3,N4,N5,L1,L2
count,1731.000000,1731.000000,1731.000000,1731.000000,1731.000000,1731.000000,1731.000000
mean,25.416522,24.867129,25.926054,25.439053,25.603697,6.057192,5.980358
std,14.441884,14.311753,14.129061,14.455839,14.450836,3.251797,3.257480
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,13.000000,13.000000,14.000000,13.000000,13.000000,3.000000,3.000000
50%,26.000000,24.000000,26.000000,25.000000,26.000000,6.000000,6.000000
75%,38.000000,37.000000,38.000000,38.000000,38.000000,9.000000,9.000000
max,50.000000,50.000000,50.000000,50.000000,50.000000,12.000000,12.000000


In [9]:
scaler = StandardScaler().fit(df.values)
transformed_dataset = scaler.transform(df.values)
transformed_df = pd.DataFrame(data=transformed_dataset, index=df.index)

In [10]:
transformed_df.head()

,0,1,2,3,4,5,6
YYYY_MMM_DD,,,,,,,
2004-02-13,0.455992,-0.619749,0.217625,1.076758,0.719634,0.905240,0.313106
2004-02-20,-0.860006,1.756608,1.491963,-1.275912,0.927294,-1.248038,-0.301043
2004-02-27,0.802307,-0.410070,-0.561137,-0.791539,0.373533,-0.325204,-0.608117
2004-03-05,0.940833,0.848001,-1.552289,-1.275912,0.511973,-0.325204,-1.529341
2004-03-12,1.287148,1.546929,-0.773527,0.177208,-0.111008,-0.632815,-0.301043


In [11]:
# All our games
number_of_rows = df.values.shape[0]
number_of_rows

1731

In [12]:
# Amount of games we need to take into consideration for prediction
window_length = 7
window_length 

7

In [13]:
# Balls counts
number_of_features = df.values.shape[1]
number_of_features

7

In [14]:
X = np.empty([ number_of_rows - window_length, window_length, number_of_features], dtype=float)
X

array([[[8.557e-321, 8.552e-321, 8.547e-321, ..., 8.537e-321,
         8.533e-321, 8.528e-321],
        [8.523e-321, 8.518e-321, 8.513e-321, ..., 8.503e-321,
         8.498e-321, 8.493e-321],
        [8.488e-321, 8.483e-321, 8.478e-321, ..., 8.468e-321,
         8.463e-321, 8.458e-321],
        ...,
        [8.419e-321, 8.414e-321, 8.409e-321, ..., 8.399e-321,
         8.394e-321, 8.389e-321],
        [8.384e-321, 8.379e-321, 8.374e-321, ..., 8.365e-321,
         8.360e-321, 8.355e-321],
        [8.350e-321, 8.345e-321, 8.340e-321, ..., 8.330e-321,
         8.325e-321, 8.320e-321]],

       [[8.315e-321, 8.310e-321, 8.305e-321, ..., 8.295e-321,
         8.290e-321, 8.285e-321],
        [8.281e-321, 8.276e-321, 8.271e-321, ..., 8.261e-321,
         8.256e-321, 8.251e-321],
        [8.246e-321, 8.241e-321, 8.236e-321, ..., 8.226e-321,
         8.221e-321, 8.216e-321],
        ...,
        [8.177e-321, 8.172e-321, 8.167e-321, ..., 8.157e-321,
         8.152e-321, 8.147e-321],
        [8.1

In [15]:
y = np.empty([ number_of_rows - window_length, number_of_features], dtype=float)
y

array([[6.12683234e-310, 6.12683234e-310, 5.04683055e-310, ...,
        1.44466615e+001, 1.44466615e+001, 1.44466615e+001],
       [1.44466615e+001, 1.44466615e+001, 1.44466615e+001, ...,
        1.44466615e+001, 1.44466615e+001, 1.44466615e+001],
       [1.44466615e+001, 1.44466615e+001, 1.44466615e+001, ...,
        1.44466615e+001, 1.44466615e+001, 1.44466615e+001],
       ...,
       [4.07895310e+000, 3.85801310e-004, 3.62360877e+001, ...,
        1.58432512e+001, 2.51968041e+001, 9.61102150e-001],
       [9.61102150e-001, 1.03966945e+000, 1.58432512e+001, ...,
        9.11823675e+000, 9.11823675e+000, 1.58432512e+001],
       [8.88253485e+000, 2.48039675e+001, 9.11823675e+000, ...,
        1.58432512e+001, 9.61102150e-001, 3.92181850e+000]])

In [16]:
for i in range(0, number_of_rows-window_length):
    X[i] = transformed_df.iloc[i : i+window_length, 0 : number_of_features]
    y[i] = transformed_df.iloc[i+window_length : i+window_length+1, 0 : number_of_features]

In [17]:
X.shape

(1724, 7, 7)

In [18]:
y.shape

(1724, 7)

In [19]:
X[0]

array([[ 0.45599175, -0.61974877,  0.21762479,  1.07675826,  0.71963358,
         0.9052404 ,  0.313106  ],
       [-0.86000621,  1.75660763,  1.49196294, -1.27591217,  0.92729401,
        -1.24803756, -0.30104299],
       [ 0.80230701, -0.41007027, -0.56113741, -0.79153885,  0.37353285,
        -0.32520415, -0.60811749],
       [ 0.94083311,  0.84800077, -1.5522893 , -1.27591217,  0.51197314,
        -0.32520415, -1.52934099],
       [ 1.28714836,  1.54692912, -0.7735271 ,  0.1772078 , -0.11100816,
        -0.63281529, -0.30104299],
       [ 1.14862226,  1.40714345,  0.50081105,  0.79997351,  0.71963358,
         0.9052404 , -0.60811749],
       [-0.1673757 ,  1.26735778, -1.62308587, -1.48350074, -1.08009018,
        -1.24803756, -0.60811749]])

In [20]:
X[1]

array([[-0.86000621,  1.75660763,  1.49196294, -1.27591217,  0.92729401,
        -1.24803756, -0.30104299],
       [ 0.80230701, -0.41007027, -0.56113741, -0.79153885,  0.37353285,
        -0.32520415, -0.60811749],
       [ 0.94083311,  0.84800077, -1.5522893 , -1.27591217,  0.51197314,
        -0.32520415, -1.52934099],
       [ 1.28714836,  1.54692912, -0.7735271 ,  0.1772078 , -0.11100816,
        -0.63281529, -0.30104299],
       [ 1.14862226,  1.40714345,  0.50081105,  0.79997351,  0.71963358,
         0.9052404 , -0.60811749],
       [-0.1673757 ,  1.26735778, -1.62308587, -1.48350074, -1.08009018,
        -1.24803756, -0.60811749],
       [-1.48337366, -0.06060609, -0.98591679,  0.73077732,  0.09665228,
        -1.24803756,  0.927255  ]])

In [21]:
y[0]

array([-1.48337366, -0.06060609, -0.98591679,  0.73077732,  0.09665228,
       -1.24803756,  0.927255  ])

In [22]:
y[1]

array([-0.1673757 , -0.41007027, -1.12750992, -1.69108931, -1.49541105,
       -1.24803756,  0.6201805 ])

In [23]:
# Recurrent Neural Netowrk (RNN) with Long Short Term Memory (LSTM)
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional, Dropout
batch_size = 100

2024-05-01 10:34:12.641338: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [24]:
# Initialising the RNN
model = Sequential()
# Adding the input layer and the LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a first Dropout layer
model.add(Dropout(0.2))
# Adding a second LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a second Dropout layer
model.add(Dropout(0.2))
# Adding a third LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = True)))
# Adding a fourth LSTM layer
model.add(Bidirectional(LSTM(240,
                        input_shape = (window_length, number_of_features),
                        return_sequences = False)))
# Adding a fourth Dropout layer
model.add(Dropout(0.2))
# Adding the first output layer
model.add(Dense(59))
# Adding the last output layer
model.add(Dense(number_of_features))

2024-05-01 10:34:19.945011: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-05-01 10:34:20.124455: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-05-01 10:34:20.124881: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-05-01 10:34:20.126758: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operation

In [25]:
from tensorflow import keras
from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate=0.0001), loss ='mse', metrics=['accuracy'])

In [40]:
model.fit(x=X, y=y, batch_size=100, epochs=10, verbose=2)

Epoch 1/10


2024-05-01 00:11:45.343182: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:428] Loaded cuDNN version 8800
2024-05-01 00:11:45.686285: I tensorflow/compiler/xla/service/service.cc:173] XLA service 0x7c1fb424cfe0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-05-01 00:11:45.686328: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (0): NVIDIA GeForce RTX 2060, Compute Capability 7.5
2024-05-01 00:11:45.718437: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2024-05-01 00:11:46.080137: I tensorflow/compiler/jit/xla_compilation_cache.cc:477] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


18/18 - 18s - loss: 1.0004 - accuracy: 0.1549 - 18s/epoch - 996ms/step
Epoch 2/10
18/18 - 0s - loss: 0.9958 - accuracy: 0.1891 - 308ms/epoch - 17ms/step
Epoch 3/10
18/18 - 0s - loss: 0.9942 - accuracy: 0.1798 - 289ms/epoch - 16ms/step
Epoch 4/10
18/18 - 0s - loss: 0.9931 - accuracy: 0.1700 - 281ms/epoch - 16ms/step
Epoch 5/10
18/18 - 0s - loss: 0.9926 - accuracy: 0.1630 - 284ms/epoch - 16ms/step
Epoch 6/10
18/18 - 0s - loss: 0.9919 - accuracy: 0.1729 - 280ms/epoch - 16ms/step
Epoch 7/10
18/18 - 0s - loss: 0.9911 - accuracy: 0.1676 - 285ms/epoch - 16ms/step
Epoch 8/10
18/18 - 0s - loss: 0.9911 - accuracy: 0.1862 - 285ms/epoch - 16ms/step
Epoch 9/10
18/18 - 0s - loss: 0.9906 - accuracy: 0.1850 - 288ms/epoch - 16ms/step
Epoch 10/10
18/18 - 0s - loss: 0.9905 - accuracy: 0.1717 - 288ms/epoch - 16ms/step


In [62]:
to_predict = df.tail(7)
#to_predict.drop([to_predict.index[-1]],axis=0, inplace=True)
to_predict

,N1,N2,N3,N4,N5,L1,L2
YYYY_MMM_DD,,,,,,,
2024-04-05,26,37,35,18,13,11,8
2024-04-09,27,46,19,23,26,2,10
2024-04-12,45,16,12,2,3,11,2
2024-04-16,39,31,46,29,22,3,7
2024-04-19,10,20,46,40,44,1,3
2024-04-23,9,49,11,6,32,2,10
2024-04-26,47,2,39,20,40,8,4


In [63]:
to_predict = np.array(to_predict)
to_predict

array([[26, 37, 35, 18, 13, 11,  8],
       [27, 46, 19, 23, 26,  2, 10],
       [45, 16, 12,  2,  3, 11,  2],
       [39, 31, 46, 29, 22,  3,  7],
       [10, 20, 46, 40, 44,  1,  3],
       [ 9, 49, 11,  6, 32,  2, 10],
       [47,  2, 39, 20, 40,  8,  4]])

In [64]:
scaled_to_predict = scaler.transform(to_predict)

In [65]:
y_pred = model.predict(np.array([scaled_to_predict]))
print("The predicted numbers in the last lottery game are:", scaler.inverse_transform(y_pred).astype(int)[0])

1/1 [==============================] - 0s 34ms/step
The predicted numbers in the last lottery game are: [25 24 15 17 14 11  6]
1/1 [==============================] - 0s 34ms/step
The predicted numbers in the last lottery game are: [25 24 15 17 14 11  6]


In [66]:
prediction = df.tail(1)
prediction = np.array(prediction)
print("The actual numbers in the last lottery game were:", prediction[0])

The actual numbers in the last lottery game were: [47  2 39 20 40  8  4]


In [ ]:
model.save("input/" + filename + "3.keras")
model.save("input/" + filename + "3.h5")

In [1]:
1730*10

17300

In [41]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bidirectional_4 (Bidirectio  multiple                 476160    
 nal)                                                            
                                                                 
 dropout_3 (Dropout)         multiple                  0         
                                                                 
 bidirectional_5 (Bidirectio  multiple                 1384320   
 nal)                                                            
                                                                 
 dropout_4 (Dropout)         multiple                  0         
                                                                 
 bidirectional_6 (Bidirectio  multiple                 1384320   
 nal)                                                            
                                                      